### ISSUE TITLE
Promotion to knight bug

### ISSUE THREAD

**Issue by SzotsGabor** [matthiaslang/jackychess#2]
It seems Jacky does not accept the pawn promotion to knight. Two examples from my just finished tournament:

[Event "Jacky Chess 0.13.0 64-bit - Oct 9"]
[Site "Szentendre"]
[Date "2022.10.11"]
[Round "22"]
[White "Chaturanga 2.4.3"]
[Black "Jacky Chess 0.13.0 64-bit"]
[Result "1-0"]
[ECO "B12"]
[Opening "Caro-Kann"]
[Time "14:59:25"]
[Variation "Advance Variation, 3...c5 4.dxc5"]
[TimeControl "120+1"]
[PlyCount "191"]

1. e4 c6 2. d4 d5 3. e5 c5 4. dxc5 e6 5. Be3 Nd7 {-0.34/11 2} 6. Bb5
{+0.44/10 4} Ne7 {-0.49/11 2} 7. Nf3 {+0.35/9 2} Nf5 {-0.33/13 2} 8. b4
{+0.28/10 4} Nxe3 {-0.17/12 3} 9. fxe3 {+0.34/12 6} a6 {-0.23/12 4} 10. Ba4
{+0.37/11 3} Be7 {-0.03/13 3} 11. Nc3 {+0.64/10 2} O-O {-0.07/13 3} 12. O-O
{+0.54/11 5} Qc7 {-0.19/13 4} 13. Qd4 {+0.40/10 2} a5 {-0.20/12 3} 14. a3
{+0.59/10 2} f6 {-0.27/12 3} 15. exf6 {+0.26/10 6} Bxf6 {+0.04/12 4} 16.
Qd3 {+0.19/11 3} Ne5 {+0.42/13 3} 17. Nb5 {+0.15/11 2} Nxf3+ {+0.43/13 3}
18. gxf3 {+0.02/11 2} Qd8 {+0.49/13 2} 19. Ra2 {+0.04/11 3} Bd7 {+0.44/11
3} 20. c4 {+0.02/10 2} dxc4 {+0.28/11 2} 21. Qxc4 {-0.07/11 7} axb4
{-0.08/12 4} 22. axb4 {+0.49/10 2} Bc6 {-0.36/11 3} 23. Bb3 {+0.98/11 3}
Bd5 {-1.01/14 3} 24. Rxa8 {+1.01/12 1} Qxa8 {-1.18/15 3} 25. Qc2 {+1.05/11
1} Qe8 {-0.82/13 2} 26. Bxd5 {+1.16/11 1} exd5 {-0.78/13 2} 27. Qd3
{+1.21/11 2} Qh5 {-0.98/13 2} 28. e4 {+1.30/10 2} Be5 {-1.10/13 2} 29.
Qxd5+ {+1.66/10 1} Kh8 {-1.07/13 2} 30. Qd2 {+1.58/10 1} Bf4 {-0.91/14 2}
31. Qe2 {+1.66/10 1} Rd8 {-0.70/13 2} 32. Nd6 {+1.38/10 2} Bxd6 {-0.91/13
2} 33. cxd6 {+1.38/12 1} Qg6+ {-0.85/13 2} 34. Kh1 {+1.53/12 2} Qxd6
{-0.99/13 2} 35. b5 {+1.51/11 2} Qf4 {-0.97/12 2} 36. Rd1 {+1.75/12 2}
Rxd1+ {-1.09/16 2} 37. Qxd1 {+1.77/13 3} h5 {-1.05/15 3} 38. Qe2 {+1.83/12
7} Qc1+ {-1.05/14 4} 39. Kg2 {+1.96/12 1} Qg5+ {-1.01/15 3} 40. Kh3
{+1.96/12 1} Kh7 {-1.22/15 2} 41. Qd3 {+1.96/11 1} Qf4 {-1.21/15 2} 42. e5+
{+1.96/11 3} Kh6 {-1.26/16 2} 43. Qe2 {+2.09/11 5} Kg6 {-1.30/17 3} 44. Kg2
{+1.99/10 1} Qg5+ {-1.16/15 2} 45. Kf1 {+2.04/10 1} Qc1+ {-1.13/16 2} 46.
Kf2 {+2.09/10 1} Qf4 {-1.13/16 1} 47. Qd3+ {+2.01/9 1} Kf7 {-1.13/16 1} 48.
Qd5+ {+1.83/9 1} Kg6 {-1.18/15 1} 49. h3 {+1.74/9 1} b6 {-1.14/13 1} 50.
Qd3+ {+2.09/9 1} Kf7 {-1.22/15 1} 51. Qd5+ {+1.88/9 1} Kg6 {0.00/17 1} 52.
Qd3+ {+2.09/9 0} Kf7 {0.00/21 1} 53. Qd6 {+1.86/9 1} Qh4+ {-0.80/15 1} 54.
Kg2 {+1.65/10 1} Qg5+ {-0.71/15 1} 55. Kf1 {+1.61/10 1} Qf5 {-0.72/15 1}
56. Qc7+ {+1.57/9 1} Kg8 {-0.70/15 1} 57. Kf2 {+1.07/10 1} Qxh3 {-0.51/14
1} 58. Ke3 {+1.04/9 0} Qe6 {-0.32/14 1} 59. Kd4 {+0.73/9 0} Qa2 {-0.38/14
1} 60. Qc6 {+0.90/9 1} Qd2+ {-0.43/14 1} 61. Ke4 {+0.88/9 0} Qb4+ {-0.14/15
1} 62. Kd3 {+0.74/10 1} Qb1+ {-0.14/15 1} 63. Kd4 {+0.99/9 1} Qb4+
{-0.14/14 1} 64. Ke3 {+0.88/10 1} Qe1+ {-0.14/15 1} 65. Kf4 {+0.86/10 2}
Qb4+ {-0.14/15 1} 66. Kf5 {+0.88/10 0} Qf8+ {-0.26/16 1} 67. Kg5 {+0.88/10
1} Qe7+ {-0.39/16 1} 68. Kf5 {+0.85/10 0} Qf8+ {0.00/17 1} 69. Kg5
{+0.88/10 0} Qe7+ {0.00/18 1} 70. Kf4 {+0.80/11 2} Qb4+ {0.00/16 1} 71. Ke3
{+0.80/10 0} Qe1+ {0.00/16 1} 72. Kd4 {+0.04/10 1} Qd2+ {0.00/16 1} 73. Ke4
{+0.69/10 0} Qb4+ {0.00/16 1} 74. Kd3 {+0.50/10 0} Qb1+ {0.00/16 1} 75. Kd4
{+0.04/10 1} Qb4+ {0.00/16 1} 76. Kd5 {+0.38/11 1} Qd2+ {-0.25/14 1} 77.
Ke6 {+0.69/10 0} Qd8 {-0.20/13 1} 78. Qc4 {+0.71/10 1} Kh7 {-0.39/14 1} 79.
Kf5 {+0.71/10 1} g6+ {-0.03/15 1} 80. Ke4 {+0.42/11 2} Qh4+ {-0.09/14 1}
81. f4 {+0.61/11 3} Qh1+ {0.00/15 1} 82. Kd4 {+0.61/10 1} Qd1+ {0.00/15 1}
83. Ke3 {+0.30/10 1} h4 {0.00/16 1} 84. e6 {+0.32/9 1} Qe1+ {0.00/16 1} 85.
Kf3 {+0.05/10 1} h3 {0.00/16 1} 86. Qa2 {+0.04/9 0} Qc3+ {+0.33/14 1} 87.
Kg4 {0.00/10 0} Qe3 {+0.48/15 1} 88. Kh4 {0.00/10 1} Qxf4+ {+0.64/15 1} 89.
Kxh3 {+1.10/1 0} Qf1+ {+0.42/15 1} 90. Kg3 {+0.35/9 0} Qd3+ {+0.41/15 1}
91. Kf4 {+0.28/9 1} Qf5+ {+0.39/15 1} 92. Ke3 {+0.36/9 0} Qxb5 {0.00/14 1}
93. Qa7+ {+0.39/9 2} Kh6 {+0.27/15 1} 94. e7 {+0.39/8 0} Kg5 {+0.96/13 1}
95. Kd4 {-0.84/9 1} Kf6 {+1.18/14 1} 96. e8=N {-0.82/9 0  Arena
Adjudication. Illegal move!} 1-0

[Event "Jacky Chess 0.13.0 64-bit - Oct 9"]
[Site "Szentendre"]
[Date "2022.10.12"]
[Round "31"]
[White "Jacky Chess 0.13.0 64-bit"]
[Black "Kingfisher 1.0 64-bit"]
[Result "0-1"]
[ECO "E84"]
[Opening "King's Indian"]
[Time "10:13:33"]
[Variation "Sämisch, Panno Main Line, 9.Nc1 e5 10.d5 Nd4 11.Nb3"]
[TimeControl "120+1"]
[PlyCount "132"]

1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6 5. f3 O-O 6. Be3 Nc6 7. Nge2 a6 8.
Qd2 Rb8 9. Nc1 e5 10. d5 {-0.18/12 2} Nd4 {-0.51/14 4} 11. Nb3 {-0.20/12 3}
c5 {-0.50/14 4} 12. Bd3 {-0.05/12 3} b5 {-0.01/13 4} 13. cxb5 {-0.03/12 3}
axb5 {-0.20/14 4} 14. Bxd4 {+0.18/12 3} cxd4 {-0.11/14 4} 15. Nxb5
{+0.39/11 3} Nh5 {-0.08/13 3} 16. Na7 {+0.35/12 3} Bd7 {+0.45/13 3} 17. Nc6
{+0.26/13 3} Bxc6 {+0.39/15 3} 18. dxc6 {-0.03/13 3} Qb6 {+0.43/14 3} 19.
Rc1 {-0.14/13 3} Rfc8 {+0.73/13 3} 20. O-O {-0.49/12 3} Nf4 {+1.18/15 3}
21. g3 {-0.65/12 3} Nxd3 {+1.27/16 3} 22. Qxd3 {-0.83/14 3} Rxc6 {+1.32/16
3} 23. Rxc6 {-0.84/12 3} Qxc6 {+1.51/15 3} 24. Ra1 {-0.83/12 3} Qa4
{+1.51/14 3} 25. h3 {-0.94/13 3} Bh6 {+2.08/16 3} 26. h4 {-0.98/13 3} Be3+
{+2.29/15 3} 27. Kh2 {-0.99/13 3} Kg7 {+2.30/15 3} 28. Kg2 {-1.11/13 3} Rc8
{+2.45/16 3} 29. Qe2 {-1.22/12 3} Qc4 {+2.60/17 3} 30. Re1 {-1.13/13 3} Qa4
{+2.60/18 3} 31. Ra1 {0.00/17 3} f6 {+2.45/16 3} 32. g4 {-1.08/12 3} Qc4
{+3.64/15 2} 33. Re1 {-1.55/14 2} Bf4 {+3.70/16 2} 34. Qxc4 {-1.47/16 2}
Rxc4 {+3.57/16 2} 35. Kf2 {-1.48/14 3} Kf7 {+3.78/15 2} 36. Ke2 {-1.66/14
3} Rc2+ {+3.86/16 2} 37. Kd3 {-1.53/15 3} Rf2 {+3.66/16 2} 38. a4 {-1.55/15
2} Rxf3+ {+3.82/15 2} 39. Kc4 {-1.44/14 2} Rf2 {+3.79/15 2} 40. Rb1
{-0.92/14 2} Rc2+ {+2.67/14 2} 41. Kd3 {-0.61/14 2} Rc7 {+2.49/15 2} 42. a5
{-0.38/13 2} Ke6 {+2.25/15 2} 43. a6 {-0.63/14 2} f5 {+1.88/16 2} 44. gxf5+
{-0.59/15 2} gxf5 {+1.54/17 2} 45. Ra1 {-0.60/15 2} Ra7 {+1.54/17 2} 46.
Nd2 {-0.50/14 2} fxe4+ {+1.76/17 2} 47. Nxe4 {-0.63/15 2} d5 {+1.76/17 2}
48. Nc5+ {-0.61/15 2} Kf5 {+1.76/16 2} 49. h5 {-0.51/12 2} Be3 {+1.81/15 2}
50. b4 {-0.46/14 2} e4+ {+2.08/17 2} 51. Ke2 {-0.55/15 2} Ke5 {+2.08/15 2}
52. Ra4 {-0.56/14 2} Bg5 {+2.81/13 2} 53. b5 {-0.60/15 2} Bd8 {+2.46/14 2}
54. Kd2 {-0.87/14 2} Bb6 {+2.32/14 2} 55. Nb7 {-0.87/15 2} d3 {+2.56/15 2}
56. Na5 {-1.17/14 2} Rc7 {+1.97/15 2} 57. Nc6+ {-0.38/15 1} Kf4 {+1.86/16
2} 58. a7 {-0.04/15 1} Be3+ {+2.25/15 2} 59. Kc3 {-1.15/15 1} d2 {+1.35/12
1} 60. Kc2 {-0.83/15 1} Bxa7 {+1.85/11 1} 61. Rxa7 {+0.76/16 1} Rxa7
{-1.37/17 1} 62. Nxa7 {+2.54/18 2} Kf3 {-2.05/17 1} 63. Kxd2 {+6.20/19 2}
Kf2 {-4.44/17 1} 64. Nc6 {+9.35/20 1} e3+ {-5.62/15 1} 65. Kc2 {+9.55/20 1}
e2 {-11.65/17 1} 66. Ne5 {+9.55/19 1} e1=N {-12.90/18 1  Arena
Adjudication. Illegal move!} 0-1

Gabor Szots, CCRL

**Comment by matthiaslang** [comment]
The bug is fixed in the Version 0.13.1.

Thanks,
Matthias
